### ISSUE TITLE
Remove HEARTBEAT

### ISSUE THREAD

**Issue by oberstet** [tavendo/WAMP#106]

**Comment by oberstet** [comment]
HEARTBEAT is removed from the spec now (RC4 branch)

**Comment by mtourne** [comment]
I have a case here where it seems like HEARTBEAT could be useful (?)

For instance if I have a caller and a callee, and the callee is not connected I get an error (normal behavior).
But if the callee pulls out right after having received the CALL message but never yields. The caller coroutine will be blocked forever.
Without a HEARTBEAT I'm not sure how to identify between a really long running CALL that will eventually YIELD, and a CALL that will never YIELD because there is no one to answer it (heartbeat would address this case).

**Comment by oberstet** [comment]
The router will detect the failed callee, and should fail the call in turn. You can also use progressive results to inform the caller about the progress of a long-running operation.

**Comment by mtourne** [comment]
Tested with crossbar (and erwa), I can definitely block a caller by interrupting the callee at the right moment.
Ps. should we move this discussion away from the heartbeat discussion ?
